[workspace]
resolver = "3"
members = ["main", "illustrator", "scribe"]
default-members = ["main"]

[workspace.dependencies]
chrono = { version = "0.4.42", default-features = false, features = ["alloc", "clock", "now", "std", "serde"] }
serde = { version = "1.0.226", features = ["derive"] }
config = { version = "0.15.17", default-features = false, features = ["toml"] }
image = { version = "0.25.8", features = ["png", "jpeg", "ico"] }
log = "0.4.28"
rbook = { version = "0.6.6", default-features = false }
thiserror = "2.0.16"

[profile.dev-opt]
inherits = "dev"
opt-level = 1
overflow-checks = false

