[package]
name = "scribble-reader"
version = "0.1.0"
authors = ["ksonny <ksonny@lotrax.org>"]
edition = "2024"
publish = false

[dependencies]
chrono = { version = "0.4.42", default-features = false, features = ["alloc", "clock", "now", "std", "serde"] }
clock = { version = "0.4.0", default-features = false }
config = { version = "0.15.17", default-features = false, features = ["toml"] }
dotenv = "0.15.0"
egui = "0.32.3"
egui-wgpu = "0.32.3"
egui-winit = "0.32.3"
egui_extras = { version = "0.32.3", features = ["svg", "image"] }
env_logger = "0.11.8"
epub = "2.1.4"
image = { version = "0.25.8", features = ["png", "jpeg", "ico"] }
lazy_static = "1.5.0"
log = "0.4.28"
lucide-icons = "0.544.0"
now = { version = "0.1.3", default-features = false }
pollster = "0.4.0"
rayon = "1.11.0"
rusqlite = { version = "0.37.0", features = ["bundled", "blob", "rusqlite-macros", "chrono"] }
rusqlite_migration = "2.3.0"
serde = { version = "1.0.226", features = ["derive"] }
serde_rusqlite = "0.40.0"
svg = "0.18.0"
thiserror = "2.0.16"
xdg = "3.0.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
winit = { version = "0.30.12" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15.1"
winit = { version = "0.30.12", features = ["android-native-activity"] }

[[bin]]
# Rename the bin to avoid https://github.com/rust-lang/cargo/issues/6313
name = "scribble-reader-desktop"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.android.signing.release]
path = "./path/to/KeyStoreFile.jks"
keystore_password = "password"

[package.metadata.android]
build_targets = ["aarch64-linux-android", "x86_64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 35
