[package]
name = "reader"
version = "0.1.0"
edition = "2024"

[dependencies]
fixed = "1.29.0"
image = { workspace = true }
log = { workspace = true }
rbook = { workspace = true }
thiserror = { workspace = true }

